ssh -i ~/.ssh/id_rsa $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER_IP << 'EOF'
    echo "Exporting environment variables..."
    export RUNTIME=production
    export JWT_SECRET_KEY="$JWT_SECRET_KEY"
    export JWT_ALGORITHM="$JWT_ALGORITHM"
    export JWT_EXPIRATION_TIME="$JWT_EXPIRATION_TIME"
    export POSTGRES_USER="$POSTGRES_USER"
    export POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
    export POSTGRES_HOST="$POSTGRES_HOST"
    export POSTGRES_DB="$POSTGRES_DB"
    export POSTGRES_PORT_ON_MACHINE="$POSTGRES_PORT_ON_MACHINE"
    export POSTGRES_PORT_IN_DOCKER="$POSTGRES_PORT_IN_DOCKER"
    export PRODUCTION_VOTING_APP_IMAGE_NAME="$PRODUCTION_VOTING_APP_IMAGE_NAME"
    echo "Environment variables exported."
EOF